name: Build & Test Spring Boot App
on:
  push:
    branches:
      - week2
  pull_request:
    branches:
      - week2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup Maven settings.xml with plaintext credentials
        run: |
          mkdir -p ~/.m2
          echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                    https://maven.apache.org/xsd/settings-1.0.0.xsd">
            <servers>
              <server>
                <id>my-private-repo</id>
                <username>'"$MAVEN_USERNAME"'</username>
                <password>'"$MAVEN_PASSWORD"'</password>
              </server>
            </servers>
          </settings>' > ~/.m2/settings.xml
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}

      - name: Build & Test with Maven (Full Debug)
        run: mvn -B clean package -e -X

      - name: Upload JAR artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: java-app-jar
          path: target/*.jar
